### ISSUE TITLE
Transfer gap closing procedure to sequence extension

### ISSUE THREAD

**Issue by a-ludi** [a-ludi/djunctor#14]
Until to now, gaps can successfully be filled. Now it is time to transfer the procedure to the extension case.

### Tasks:
- [x] extend `CoordinateTransform` so extensions can be added
- [x] adjust `DJunctor.getInsertionInfo` to the extension case
- [x] create `DJunctor.getExtensionSequenceSlice` analogue to `DJunctor.getGapSequenceSlice`
- [x] refactor `DJunctor.fillGap`
- [x] implement `DJunctor.extendContig` analogue to `DJunctor.fillGap`
