### ISSUE TITLE
Improve pre-consensus alignment

### ISSUE THREAD

**Issue by a-ludi** [a-ludi/djunctor#29]
In order to compute the consensus of a pile up an alignment of the cropped reads must be computed. Ideally, we would want to use the information on the (relative) location of the cropped reads we gained during prior analysis and selection.

### Tasks
- [ ] Examine examples of the alignments in the current state.
- [ ] Add example to integration tests which shows difficulties.
- [ ] Try using `lasfilteralignments` to reduce faulty alignments.
- [ ] Try adding unique (random) adapters to the cropped reads acting as anchors.
