### ISSUE TITLE
Move loop structure out of the main algorithm

### ISSUE THREAD

**Issue by a-ludi** [a-ludi/djunctor#46]
Applying this algorithm iteratively can be done from outside if given some intermediate results. Thus, the loop should be eliminated and opportunities given to access the intermediate results.

# What needs to be done?
- [x] adjust algorithmic structure as sketched below (issue #47)
- [x] make sequential output (issue #45)
- [x] add opportunity to output of the candidate set of reads (issue #41)
- [x] add opportunity to make use of user-input masks (and reads) (issue #48)

## Sketch of algorithmic structure
```pascal
// Initialization
maskBadRegions()
filterReadAlignments()
// Close Gaps
buildPileUps()
for each pileUp do
    selectGoodReads()
    cropAndValidateReads()
    buildConsensus()
// Finish
pruneOverfilledGaps()
generateOutput()
```
